// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAod1j3Yoww1vFT7LOvh_hIhHAwP4mhuCE',
    appId: '1:556038236144:web:7588368c56eda1ef671f35',
    messagingSenderId: '556038236144',
    projectId: 'cordova-app-project-66bf5',
    authDomain: 'cordova-app-project-66bf5.firebaseapp.com',
    storageBucket: 'cordova-app-project-66bf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqznu3RJ-jO1UOjxeZr0tchgijmgJuLk',
    appId: '1:556038236144:android:2a1bf7901e3735c7671f35',
    messagingSenderId: '556038236144',
    projectId: 'cordova-app-project-66bf5',
    storageBucket: 'cordova-app-project-66bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMHyg3BWb2KvFbBut3066LlEJuVGQ04QY',
    appId: '1:556038236144:ios:9030f77117a198cf671f35',
    messagingSenderId: '556038236144',
    projectId: 'cordova-app-project-66bf5',
    storageBucket: 'cordova-app-project-66bf5.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCordova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMHyg3BWb2KvFbBut3066LlEJuVGQ04QY',
    appId: '1:556038236144:ios:9030f77117a198cf671f35',
    messagingSenderId: '556038236144',
    projectId: 'cordova-app-project-66bf5',
    storageBucket: 'cordova-app-project-66bf5.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCordova',
  );
}
